import type { SimInput } from './types';

export interface Preset {
  label: string;
  icon: string;
  description: string;
  values: Partial<SimInput>;
}

export const PRESETS: Preset[] = [
  {
    label: '都心RC区分',
    icon: '🏙️',
    description: '都心部のRCマンション区分。高値・低利回り・安定空室率',
    values: {
      propertyName: '都心RC区分マンション',
      propertyType: '区分マンション',
      location: '東京都',
      managementType: 'shukkin',
      propertyPrice: 50_000_000,
      equity: 5_000_000,
      expenses: 1_500_000,
      rate: 0.018,
      termYears: 35,
      monthlyRent: 150_000,
      managementFee: 12_000,
      repairFund: 10_000,
      otherExpenses: 0,
      vacancyRate: 0.05,
      fixedAssetTax: 100_000,
      buildingRatio: 0.60,
      structureDepYears: 47,
      equipmentDepYears: 15,
      holdingYears: 10,
      growthRate: 0.000,
      structurePrice: 0,
      equipmentPrice: 0,
    },
  },
  {
    label: '地方木造戸建',
    icon: '🏡',
    description: '地方の木造戸建て。安価・高利回り・空室リスク高め',
    values: {
      propertyName: '地方木造戸建て',
      propertyType: '戸建て',
      location: '地方',
      managementType: 'shukkin',
      propertyPrice: 12_000_000,
      equity: 2_000_000,
      expenses: 400_000,
      rate: 0.025,
      termYears: 25,
      monthlyRent: 65_000,
      managementFee: 5_000,
      repairFund: 8_000,
      otherExpenses: 0,
      vacancyRate: 0.12,
      fixedAssetTax: 50_000,
      buildingRatio: 0.50,
      structureDepYears: 22,
      equipmentDepYears: 10,
      holdingYears: 10,
      growthRate: -0.005,
      structurePrice: 0,
      equipmentPrice: 0,
    },
  },
  {
    label: '一棟アパート',
    icon: '🏗️',
    description: '地方の軽量鉄骨一棟アパート。中規模・分散リスク',
    values: {
      propertyName: '地方軽鉄一棟アパート',
      propertyType: '一棟アパート',
      location: '地方',
      managementType: 'shukkin',
      propertyPrice: 60_000_000,
      equity: 6_000_000,
      expenses: 1_800_000,
      rate: 0.022,
      termYears: 30,
      monthlyRent: 350_000,
      managementFee: 25_000,
      repairFund: 30_000,
      otherExpenses: 10_000,
      vacancyRate: 0.10,
      fixedAssetTax: 150_000,
      buildingRatio: 0.55,
      structureDepYears: 27,
      equipmentDepYears: 12,
      holdingYears: 10,
      growthRate: -0.003,
      structurePrice: 0,
      equipmentPrice: 0,
    },
  },
  {
    label: '都心一棟RC',
    icon: '🏢',
    description: '都心RCの一棟マンション。高額・安定・長期保有向き',
    values: {
      propertyName: '都心RC一棟マンション',
      propertyType: '一棟マンション',
      location: '東京都',
      managementType: 'shukkin',
      propertyPrice: 200_000_000,
      equity: 30_000_000,
      expenses: 5_000_000,
      rate: 0.016,
      termYears: 35,
      monthlyRent: 600_000,
      managementFee: 40_000,
      repairFund: 50_000,
      otherExpenses: 20_000,
      vacancyRate: 0.05,
      fixedAssetTax: 400_000,
      buildingRatio: 0.65,
      structureDepYears: 47,
      equipmentDepYears: 15,
      holdingYears: 15,
      growthRate: 0.005,
      structurePrice: 0,
      equipmentPrice: 0,
    },
  },
  {
    label: '商業テナント',
    icon: '🏪',
    description: '地方の商業物件テナント。高利回り・業態リスクあり',
    values: {
      propertyName: '地方商業テナント',
      propertyType: '商業',
      location: '地方',
      managementType: 'self',
      propertyPrice: 30_000_000,
      equity: 5_000_000,
      expenses: 900_000,
      rate: 0.030,
      termYears: 20,
      monthlyRent: 200_000,
      managementFee: 10_000,
      repairFund: 20_000,
      otherExpenses: 5_000,
      vacancyRate: 0.15,
      fixedAssetTax: 80_000,
      buildingRatio: 0.50,
      structureDepYears: 34,
      equipmentDepYears: 10,
      holdingYears: 8,
      growthRate: -0.010,
      structurePrice: 0,
      equipmentPrice: 0,
    },
  },
];
