// CSV → TypeScript 変換スクリプト
import { readFileSync, writeFileSync } from 'fs';

const csv = readFileSync('C:/Users/reale/Downloads/loan_checker_137banks.csv', 'utf-8');

// タグ自動判定
function detectTags(features, name) {
  const f = features + ' ' + name;
  const tags = [];
  if (/がん100|がん保障.*上乗せな|がん.*無料/.test(f)) tags.push('がん100団信');
  if (/三大疾病|3大疾病/.test(f)) tags.push('三大疾病');
  if (/全疾病|全傷病/.test(f)) tags.push('全疾病団信');
  if (/ペアローン|連生団信/.test(f)) tags.push('ペアローン');
  if (/単身|1K|1DK/.test(f)) tags.push('単身対応');
  if (/狭小|40㎡|30㎡|25㎡/.test(f)) tags.push('狭小物件');
  if (/外国籍|永住権なし/.test(f)) tags.push('外国籍OK');
  if (/旧耐震/.test(f)) tags.push('旧耐震OK');
  if (/自営業|個人事業主/.test(f)) tags.push('自営業OK');
  if (/産休|育休/.test(f)) tags.push('育休産休OK');
  if (/借換|借り換え/.test(f)) tags.push('借換え対応');
  if (/50年/.test(f)) tags.push('50年ローン');
  if (/諸費用.*10%|諸費用.*借入可|諸費用込/.test(f)) tags.push('諸費用込み');
  if (/おまとめ/.test(f)) tags.push('おまとめローン');
  if (/リフォーム/.test(f)) tags.push('リフォーム費用込');
  if (/転職/.test(f)) tags.push('転職者OK');
  return tags;
}

// エリア自動判定（都道府県 + 全国 + 主要エリア）
const PREFECTURE_MAP = {
  '北海道': '北海道・東北',
  '青森': '北海道・東北', '岩手': '北海道・東北', '宮城': '北海道・東北',
  '秋田': '北海道・東北', '山形': '北海道・東北', '福島': '北海道・東北',
  '茨城': '関東', '栃木': '関東', '群馬': '関東',
  '埼玉': '関東', '千葉': '関東', '東京': '関東', '神奈川': '関東',
  '新潟': '中部・北陸', '富山': '中部・北陸', '石川': '中部・北陸', '福井': '中部・北陸',
  '山梨': '中部・北陸', '長野': '中部・北陸', '岐阜': '中部・北陸',
  '静岡': '中部・北陸', '愛知': '中部・北陸', '三重': '中部・北陸',
  '滋賀': '近畿', '京都': '近畿', '大阪': '近畿',
  '兵庫': '近畿', '奈良': '近畿', '和歌山': '近畿',
  '鳥取': '中国・四国', '島根': '中国・四国', '岡山': '中国・四国',
  '広島': '中国・四国', '山口': '中国・四国',
  '徳島': '中国・四国', '香川': '中国・四国', '愛媛': '中国・四国', '高知': '中国・四国',
  '福岡': '九州・沖縄', '佐賀': '九州・沖縄', '長崎': '九州・沖縄',
  '熊本': '九州・沖縄', '大分': '九州・沖縄', '宮崎': '九州・沖縄',
  '鹿児島': '九州・沖縄', '沖縄': '九州・沖縄',
};

const REGION_GROUPS = ['北海道・東北', '関東', '中部・北陸', '近畿', '中国・四国', '九州・沖縄'];

function detectAreas(features) {
  // 「全国保証」「全国銀行」等の固有名詞を除去してから判定
  const f = features.replace(/全国保証|全国銀行|全国勤労者福祉/g, '__HOSHO__');
  // 全国対応（純粋な"全国"が残っている場合）
  if (/全国/.test(f)) return ['全国'];

  const regionSet = new Set();

  // 都道府県名でマッチング
  for (const [pref, region] of Object.entries(PREFECTURE_MAP)) {
    if (f.includes(pref)) {
      regionSet.add(region);
    }
  }

  // 明示的なエリア表記
  if (/首都圏|関東/.test(f)) regionSet.add('関東');
  if (/関西|近畿/.test(f)) regionSet.add('近畿');
  if (/東海/.test(f)) regionSet.add('中部・北陸');
  if (/九州/.test(f)) regionSet.add('九州・沖縄');
  if (/東北/.test(f)) regionSet.add('北海道・東北');
  if (/北海道/.test(f)) regionSet.add('北海道・東北');
  if (/四国/.test(f)) regionSet.add('中国・四国');
  if (/中国地方/.test(f)) regionSet.add('中国・四国');

  // エリア特定なし→全国扱い
  if (regionSet.size === 0) return ['全国'];

  // 順番を地域グループ順に
  return REGION_GROUPS.filter(r => regionSet.has(r));
}

function parseRate(s) {
  if (!s || s.trim() === '') return null;
  return parseFloat(s.replace('%','').trim());
}

function parseMoney(s) {
  if (!s || s === '-' || s.trim() === '') return 0;
  return parseInt(s.replace(/[¥,]/g,'').trim()) || 0;
}

function parseMaxLoan(s) {
  if (!s) return 0;
  const m = s.match(/([\d,]+)万円まで/);
  return m ? parseInt(m[1].replace(/,/g,'')) : 0;
}

// CSVパース（クォート対応）
function parseCSV(text) {
  const lines = text.split('\n').filter(l => l.trim());
  const rows = [];
  for (const line of lines.slice(1)) {
    const cells = [];
    let cur = '';
    let inQ = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (c === '"') { inQ = !inQ; continue; }
      if (c === ',' && !inQ) { cells.push(cur); cur = ''; continue; }
      cur += c;
    }
    cells.push(cur);
    if (cells.length >= 11) rows.push(cells);
  }
  return rows;
}

const rows = parseCSV(csv);
const banks = rows.map(c => {
  const rate = parseRate(c[3]);
  const prevRate = parseRate(c[4]);
  const fee = parseMoney(c[6]);
  const maxLoan = parseMaxLoan(c[9]);
  const features = c[10]?.trim() || '';
  const name = c[1]?.trim() || '';
  const tags = detectTags(features, name);
  const areas = detectAreas(features);

  // 名称に「固定」が含まれる場合は固定として扱う（CSV誤記対策）
  const csvType = c[2]?.trim();
  const nameHasFixed = /固定/.test(name) && !/固定費|固定資産/.test(name);
  const rateType = (csvType === '固定' || nameHasFixed) ? '固定' : '変動';

  return {
    id: `bank-${c[0]}`,
    no: parseInt(c[0]),
    name,
    rateType,
    rate: rate ?? 0,
    prevMonthRate: prevRate ?? null,
    monthlyPayment: parseMoney(c[5]),
    fee,
    maxLoan,
    features,
    tags,
    areas,
  };
});

// 各エリアのカバー銀行数を出力
const areaCounts = {};
for (const b of banks) {
  for (const a of b.areas) {
    areaCounts[a] = (areaCounts[a] || 0) + 1;
  }
}
console.log('Area coverage:', areaCounts);

const ts = `// 住宅ローン金融機関データ 137件
// Source: loan_checker_137banks.csv (2026-04 版)
// Auto-generated by scripts/convert-banks.mjs

export type HomeLoan137Tag =
  | 'がん100団信' | '三大疾病' | '全疾病団信'
  | 'ペアローン' | '単身対応' | '狭小物件'
  | '外国籍OK' | '旧耐震OK' | '自営業OK'
  | '育休産休OK' | '借換え対応' | '50年ローン'
  | '諸費用込み' | 'おまとめローン' | 'リフォーム費用込'
  | '転職者OK';

export type HomeLoan137Area =
  | '全国'
  | '北海道・東北'
  | '関東'
  | '中部・北陸'
  | '近畿'
  | '中国・四国'
  | '九州・沖縄';

export const AREA_LABELS: HomeLoan137Area[] = [
  '全国', '北海道・東北', '関東', '中部・北陸', '近畿', '中国・四国', '九州・沖縄'
];

export interface HomeLoan137 {
  id: string;
  no: number;
  name: string;
  rateType: '変動' | '固定';
  rate: number;              // %
  prevMonthRate: number | null;
  monthlyPayment: number;    // 円 (3000万・35年基準 ※ローンチェッカー掲載値)
  fee: number;               // 円
  maxLoan: number;           // 万円
  features: string;
  tags: HomeLoan137Tag[];
  areas: HomeLoan137Area[];  // 対応エリア（地方）
}

export const HOME_LOAN_137: HomeLoan137[] = ${JSON.stringify(banks, null, 2)};

// 思考別プリセットフィルター
export const PREFERENCE_PRESETS = [
  { id: 'rate',      label: '💰 金利重視',     desc: '変動金利0.9%以下',    filter: (b: HomeLoan137) => b.rateType === '変動' && b.rate <= 0.9 },
  { id: 'cancer',    label: '🏥 がん100団信',   desc: 'がん診断でローン消滅', filter: (b: HomeLoan137) => b.tags.includes('がん100団信') },
  { id: 'all-ill',   label: '🛡 全疾病団信',    desc: '全疾病保障付き',       filter: (b: HomeLoan137) => b.tags.includes('全疾病団信') },
  { id: 'fee',       label: '💳 諸費用重視',    desc: '手数料33万円以下',     filter: (b: HomeLoan137) => b.fee <= 330000 },
  { id: 'single',    label: '👤 単身・狭小',    desc: '単身・狭小物件に強い', filter: (b: HomeLoan137) => b.tags.includes('単身対応') || b.tags.includes('狭小物件') },
  { id: 'pair',      label: '👫 ペアローン',    desc: 'ペアローン対応',       filter: (b: HomeLoan137) => b.tags.includes('ペアローン') },
  { id: 'foreign',   label: '🌍 外国籍OK',      desc: '永住権なしも検討可',   filter: (b: HomeLoan137) => b.tags.includes('外国籍OK') },
  { id: 'old-quake', label: '🏗 旧耐震OK',      desc: '旧耐震物件対応',       filter: (b: HomeLoan137) => b.tags.includes('旧耐震OK') },
  { id: 'self-emp',  label: '💼 自営業・個人',  desc: '自営業・個人事業主OK', filter: (b: HomeLoan137) => b.tags.includes('自営業OK') },
  { id: 'parental',  label: '👶 育休・産休中',  desc: '育休産休中も審査可',   filter: (b: HomeLoan137) => b.tags.includes('育休産休OK') },
  { id: 'long',      label: '📅 50年ローン',    desc: '最長50年借入可',       filter: (b: HomeLoan137) => b.tags.includes('50年ローン') },
  { id: 'refi',      label: '🔄 借換え重視',    desc: '借換え対応あり',       filter: (b: HomeLoan137) => b.tags.includes('借換え対応') },
  { id: 'misc-cost', label: '🧾 諸費用込み',    desc: '諸費用を借入に含める', filter: (b: HomeLoan137) => b.tags.includes('諸費用込み') },
  { id: 'fixed',     label: '📌 固定金利',      desc: '金利変動リスクなし',   filter: (b: HomeLoan137) => b.rateType === '固定' },
  { id: 'reform',    label: '🏠 リフォーム込',  desc: 'リフォーム費用も借入', filter: (b: HomeLoan137) => b.tags.includes('リフォーム費用込') },
] as const;
`;

writeFileSync('C:/Users/reale/terass-sim/src/lib/data/homeLoan137.ts', ts, 'utf-8');
console.log(`✅ Generated ${banks.length} banks → src/lib/data/homeLoan137.ts`);
