// CSV → TypeScript 変換スクリプト
import { readFileSync, writeFileSync } from 'fs';

const csv = readFileSync('C:/Users/reale/Downloads/loan_checker_137banks.csv', 'utf-8');

// タグ自動判定
function detectTags(features, name) {
  const f = features + ' ' + name;
  const tags = [];
  if (/がん100|がん保障.*上乗せな|がん.*無料/.test(f)) tags.push('がん100団信');
  if (/三大疾病|3大疾病/.test(f)) tags.push('三大疾病');
  if (/全疾病|全傷病/.test(f)) tags.push('全疾病団信');
  if (/ペアローン|連生団信/.test(f)) tags.push('ペアローン');
  if (/単身|1K|1DK/.test(f)) tags.push('単身対応');
  if (/狭小|40㎡|30㎡|25㎡/.test(f)) tags.push('狭小物件');
  if (/外国籍|永住権なし/.test(f)) tags.push('外国籍OK');
  if (/旧耐震/.test(f)) tags.push('旧耐震OK');
  if (/自営業|個人事業主/.test(f)) tags.push('自営業OK');
  if (/産休|育休/.test(f)) tags.push('育休産休OK');
  if (/借換|借り換え/.test(f)) tags.push('借換え対応');
  if (/50年/.test(f)) tags.push('50年ローン');
  if (/諸費用.*10%|諸費用.*借入可|諸費用込/.test(f)) tags.push('諸費用込み');
  if (/おまとめ/.test(f)) tags.push('おまとめローン');
  if (/リフォーム/.test(f)) tags.push('リフォーム費用込');
  if (/転職/.test(f)) tags.push('転職者OK');
  return tags;
}

function parseRate(s) {
  if (!s || s.trim() === '') return null;
  return parseFloat(s.replace('%','').trim());
}

function parseMoney(s) {
  if (!s || s === '-' || s.trim() === '') return 0;
  return parseInt(s.replace(/[¥,]/g,'').trim()) || 0;
}

function parseMaxLoan(s) {
  if (!s) return 0;
  const m = s.match(/([\d,]+)万円まで/);
  return m ? parseInt(m[1].replace(/,/g,'')) : 0;
}

// CSVパース（クォート対応）
function parseCSV(text) {
  const lines = text.split('\n').filter(l => l.trim());
  const rows = [];
  for (const line of lines.slice(1)) {
    const cells = [];
    let cur = '';
    let inQ = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (c === '"') { inQ = !inQ; continue; }
      if (c === ',' && !inQ) { cells.push(cur); cur = ''; continue; }
      cur += c;
    }
    cells.push(cur);
    if (cells.length >= 11) rows.push(cells);
  }
  return rows;
}

const rows = parseCSV(csv);
const banks = rows.map(c => {
  const rate = parseRate(c[3]);
  const prevRate = parseRate(c[4]);
  const fee = parseMoney(c[6]);
  const maxLoan = parseMaxLoan(c[9]);
  const features = c[10]?.trim() || '';
  const name = c[1]?.trim() || '';
  const tags = detectTags(features, name);

  return {
    id: `bank-${c[0]}`,
    no: parseInt(c[0]),
    name,
    rateType: c[2]?.trim() === '固定' ? '固定' : '変動',
    rate: rate ?? 0,
    prevMonthRate: prevRate ?? null,
    monthlyPayment: parseMoney(c[5]),
    fee,
    maxLoan,
    features,
    tags,
  };
});

const ts = `// 住宅ローン金融機関データ 137件
// Source: loan_checker_137banks.csv (2026-04 版)
// Auto-generated by scripts/convert-banks.mjs

export type HomeLoan137Tag =
  | 'がん100団信' | '三大疾病' | '全疾病団信'
  | 'ペアローン' | '単身対応' | '狭小物件'
  | '外国籍OK' | '旧耐震OK' | '自営業OK'
  | '育休産休OK' | '借換え対応' | '50年ローン'
  | '諸費用込み' | 'おまとめローン' | 'リフォーム費用込'
  | '転職者OK';

export interface HomeLoan137 {
  id: string;
  no: number;
  name: string;
  rateType: '変動' | '固定';
  rate: number;              // %
  prevMonthRate: number | null;
  monthlyPayment: number;    // 円 (4000万・35年基準)
  fee: number;               // 円
  maxLoan: number;           // 万円
  features: string;
  tags: HomeLoan137Tag[];
}

export const HOME_LOAN_137: HomeLoan137[] = ${JSON.stringify(banks, null, 2)};

// 思考別プリセットフィルター
export const PREFERENCE_PRESETS = [
  { id: 'rate',      label: '💰 金利重視',     desc: '変動金利0.9%以下',    filter: (b: HomeLoan137) => b.rateType === '変動' && b.rate <= 0.9 },
  { id: 'cancer',    label: '🏥 がん100団信',   desc: 'がん診断でローン消滅', filter: (b: HomeLoan137) => b.tags.includes('がん100団信') },
  { id: 'all-ill',   label: '🛡 全疾病団信',    desc: '全疾病保障付き',       filter: (b: HomeLoan137) => b.tags.includes('全疾病団信') },
  { id: 'fee',       label: '💳 諸費用重視',    desc: '手数料33万円以下',     filter: (b: HomeLoan137) => b.fee <= 330000 },
  { id: 'single',    label: '👤 単身・狭小',    desc: '単身・狭小物件に強い', filter: (b: HomeLoan137) => b.tags.includes('単身対応') || b.tags.includes('狭小物件') },
  { id: 'pair',      label: '👫 ペアローン',    desc: 'ペアローン対応',       filter: (b: HomeLoan137) => b.tags.includes('ペアローン') },
  { id: 'foreign',   label: '🌍 外国籍OK',      desc: '永住権なしも検討可',   filter: (b: HomeLoan137) => b.tags.includes('外国籍OK') },
  { id: 'old-quake', label: '🏗 旧耐震OK',      desc: '旧耐震物件対応',       filter: (b: HomeLoan137) => b.tags.includes('旧耐震OK') },
  { id: 'self-emp',  label: '💼 自営業・個人',  desc: '自営業・個人事業主OK', filter: (b: HomeLoan137) => b.tags.includes('自営業OK') },
  { id: 'parental',  label: '👶 育休・産休中',  desc: '育休産休中も審査可',   filter: (b: HomeLoan137) => b.tags.includes('育休産休OK') },
  { id: 'long',      label: '📅 50年ローン',    desc: '最長50年借入可',       filter: (b: HomeLoan137) => b.tags.includes('50年ローン') },
  { id: 'refi',      label: '🔄 借換え重視',    desc: '借換え対応あり',       filter: (b: HomeLoan137) => b.tags.includes('借換え対応') },
  { id: 'misc-cost', label: '🧾 諸費用込み',    desc: '諸費用を借入に含める', filter: (b: HomeLoan137) => b.tags.includes('諸費用込み') },
  { id: 'fixed',     label: '📌 固定金利',      desc: '金利変動リスクなし',   filter: (b: HomeLoan137) => b.rateType === '固定' },
  { id: 'reform',    label: '🏠 リフォーム込',  desc: 'リフォーム費用も借入', filter: (b: HomeLoan137) => b.tags.includes('リフォーム費用込') },
] as const;
`;

writeFileSync('C:/Users/reale/terass-sim/src/lib/data/homeLoan137.ts', ts, 'utf-8');
console.log(`✅ Generated ${banks.length} banks → src/lib/data/homeLoan137.ts`);
